"""added quiz1 col

Revision ID: 502d7ca01a73
Revises: 12cf87a661fd
Create Date: 2020-12-19 18:26:12.194833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d7ca01a73'
down_revision = '12cf87a661fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quiz1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quiz1')
    # ### end Alembic commands ###
