"""added quiz score cols for tree, queue

Revision ID: 54bc25766877
Revises: 4fe31ef4e30e
Create Date: 2020-12-20 15:43:19.710466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bc25766877'
down_revision = '4fe31ef4e30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quizQu', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('quizTr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quizTr')
    op.drop_column('user', 'quizQu')
    # ### end Alembic commands ###
